# What this fork adds to `components-tests`, listed here so that upstream's list stays upstream's.
# Paths are relative to `apps/components_tests`, which is where this is included from.
set(RTX_TEST_FILES
    rtx/allocations.cpp
    rtx/allocations.hpp
    rtx/alphaimage.cpp
    rtx/bloompass.cpp
    rtx/bluenoise.cpp
    rtx/bottomlevelstore.cpp
    rtx/buffer.cpp
    rtx/cellgrid.cpp
    rtx/cellring.cpp
    rtx/cloudshell.cpp
    rtx/colour.cpp
    rtx/commands.cpp
    rtx/compositequeue.cpp
    rtx/computepipeline.cpp
    rtx/device.cpp
    rtx/dispatch.cpp
    rtx/dlss.cpp
    rtx/extractor/fixture.hpp
    rtx/extractor/lights.cpp
    rtx/extractor/materials.cpp
    rtx/extractor/particles.cpp
    rtx/extractor/retire.cpp
    rtx/extractor/skinning.cpp
    rtx/extractor/stats.cpp
    rtx/extractor/walk.cpp
    rtx/fallbackseed.cpp
    rtx/fogbuilder.cpp
    rtx/frameclock.cpp
    rtx/frameimage.cpp
    rtx/frameoptions.cpp
    rtx/framering.cpp
    rtx/frames.cpp
    rtx/frameworld.cpp
    rtx/geometry.hpp
    rtx/gputimer.cpp
    rtx/graphlight.hpp
    rtx/groundreader.cpp
    rtx/guipass.cpp
    rtx/guiquad.hpp
    rtx/guitextures.cpp
    rtx/harness.cpp
    rtx/harness.hpp
    rtx/instancerecord.cpp
    rtx/layers.hpp
    rtx/lightbuilder.cpp
    rtx/lightgrid.cpp
    rtx/memory.cpp
    rtx/mipchainpass.cpp
    rtx/meshreader.cpp
    rtx/mipchain.cpp
    rtx/mirroridentity.cpp
    rtx/monitor.cpp
    rtx/moonbuilder.cpp
    rtx/nodekind.cpp
    rtx/offscreentrace.cpp
    rtx/parallel.cpp
    rtx/physicaldevice.cpp
    rtx/pipelinecache.cpp
    rtx/probe.cpp
    rtx/readstamp.cpp
    rtx/reconstruction.cpp
    rtx/requirements.cpp
    rtx/result.cpp
    rtx/ripplepass.cpp
    rtx/runs.cpp
    rtx/scenedesc.cpp
    rtx/sceneuploader.cpp
    rtx/shading.cpp
    rtx/shadingmap.cpp
    rtx/shapefold.cpp
    rtx/groundcompositepass.cpp
    rtx/shadingpass.cpp
    rtx/skinpass.cpp
    rtx/skybuilder.cpp
    rtx/skylight.cpp
    rtx/slots.cpp
    rtx/slottable.cpp
    rtx/sourcetree.cpp
    rtx/spritelight.cpp
    rtx/spritelightpass.cpp
    rtx/stresspass.cpp
    rtx/spritelistsize.cpp
    rtx/spritepasses.cpp
    rtx/statistics.hpp
    rtx/stepped.cpp
    rtx/structurestorage.cpp
    rtx/sun.cpp
    rtx/surface.cpp
    rtx/templatewalk.cpp
    rtx/testtexture.hpp
    rtx/texels.cpp
    rtx/texturearray.cpp
    rtx/texturebuilder.cpp
    rtx/tracepipeline.cpp
    rtx/visibility/filter.cpp
    rtx/visibility/fixture.hpp
    rtx/visibility/fog.cpp
    rtx/visibility/frame.cpp
    rtx/visibility/framecost.cpp
    rtx/visibility/light.cpp
    rtx/visibility/sea.cpp
    rtx/visibility/sky.cpp
    rtx/visibility/sprites.cpp
    rtx/visibility/surfaces.cpp
    rtx/visibility/water.cpp
    rtx/wavecascade.cpp
    rtx/wavefield.cpp
    rtx/waveline.cpp
    rtx/wavemoments.hpp
    rtx/wavepass.cpp
    rtx/wavespectrum.cpp
    rtx/worker.cpp
    rtxbench/benchrecord.cpp
    rtxbench/benchrun.cpp
    rtxbench/benchspec.cpp
    rtxbench/framehashes.cpp
    rtxbench/frametimes.cpp
    rtxbench/gpuclock.cpp
    rtxbench/runrecord.cpp
    rtxbench/scenedigest.cpp
    rtxtool/compare.cpp
    rtxtool/options.cpp
    rtxtool/run.cpp
    sky/skyclock.cpp
    sky/sundisc.cpp
    sky/timeofday.cpp
)

# What is read off a fifo, where the platform has one.
if (NOT WIN32)
    list(APPEND RTX_TEST_FILES rtxbench/perffifo.cpp)
endif()

# Reads a NIF through upstream's loader, whose headers are not warning-free under the extra
# checks, so it takes the errors alone.
set(RTX_TEST_FILES_UPSTREAM
    rtx/nifsurface.cpp
)
